//! HTML rendering: token styling plus fragment-span injection.
//!
//! Fragment spans and token spans interleave: a fragment boundary may fall
//! inside a token and vice versa, so text is cut at the union of both
//! boundary sets. Fragment spans nest (splitting ranges where partial
//! overlaps require it) and token spans live at the innermost level.

use std::cmp::Ordering;
use std::collections::HashMap;
use std::fmt::Write;

use giallo::{Color, FontStyle, HighlightedText, Style, ThemeVariant};
use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

/// One resolved highlight range on one line, in grapheme columns. Whole-line
/// (`^^`) ranges are lowered to one full-width `Lines` range per covered
/// line before rendering.
#[derive(Debug, Clone)]
pub struct LineRange {
    pub start_col: usize,
    /// May extend past the end of the line: the rendered line is padded with
    /// spaces inside the highlight span ("virtual space").
    pub end_col: usize,
    pub index: u32,
    pub kind: RangeKind,
    /// Whether this is the first rendered piece of its source range: the
    /// continuation pieces get an extra class so styling can anchor markers
    /// (like the arrow) to range starts only.
    pub first: bool,
    pub note: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RangeKind {
    /// `fragment highlight-code`: the inline underline style.
    Inline,
    /// `fragment highlight-lines`: the whole-line style.
    Lines,
}

/// Deduplicates token styles into CSS classes across a whole run, so one
/// generated stylesheet serves every snippet.
#[derive(Debug)]
pub struct StyleSheet {
    /// The theme's default style, which the block itself carries; only
    /// tokens that differ from it get a class.
    default: Style,
    classes: Vec<Style>,
    by_style: HashMap<Style, usize>,
}

impl StyleSheet {
    pub fn new(default: Style) -> Self {
        Self {
            default,
            classes: Vec::new(),
            by_style: HashMap::new(),
        }
    }

    /// The class for a token style, or None for the default style.
    fn class_for(&mut self, style: Style) -> Option<String> {
        if style == self.default {
            return None;
        }
        let id = *self.by_style.entry(style).or_insert_with(|| {
            self.classes.push(style);
            self.classes.len() - 1
        });
        Some(format!("hl-t{id}"))
    }

    /// Renders the generated stylesheet (SCSS-compatible plain CSS). The
    /// block's background is left to the site's own stylesheets.
    pub fn to_scss(&self) -> String {
        let mut out = String::from("// Generated by tools/hl. Do not edit; regenerate instead.\n");
        let _ = writeln!(
            out,
            "pre.hl {{\n  color: {};\n}}",
            css_color(self.default.foreground)
        );
        for (id, style) in self.classes.iter().enumerate() {
            let _ = writeln!(out, ".hl-t{id} {{");
            if style.foreground != self.default.foreground {
                let _ = writeln!(out, "  color: {};", css_color(style.foreground));
            }
            if style.background != self.default.background {
                let _ = writeln!(out, "  background-color: {};", css_color(style.background));
            }
            if style.font_style.contains(FontStyle::BOLD) {
                out.push_str("  font-weight: bold;\n");
            }
            if style.font_style.contains(FontStyle::ITALIC) {
                out.push_str("  font-style: italic;\n");
            }
            if style.font_style.contains(FontStyle::UNDERLINE) {
                out.push_str("  text-decoration: underline;\n");
            }
            if style.font_style.contains(FontStyle::STRIKETHROUGH) {
                out.push_str("  text-decoration: line-through;\n");
            }
            out.push_str("}\n");
        }
        out
    }
}

/// A theme colour as CSS, with the site's one substitution: dracula's
/// comment grey is too dark to read from the back of a room.
fn css_color(color: Color) -> String {
    match color.as_hex().to_lowercase().as_str() {
        "#6272a4" => "#9daad2".to_string(),
        hex => hex.to_string(),
    }
}

/// Options for rendering one snippet.
#[derive(Debug)]
pub struct SnippetOptions {
    pub line_numbers: bool,
    pub ln_start: Option<i64>,
    /// Display name for the language badge (e.g. "C++"), when the language
    /// gets one.
    pub lang_label: Option<String>,
}

impl Default for SnippetOptions {
    /// Lines are numbered unless a fence opts out.
    fn default() -> Self {
        Self {
            line_numbers: true,
            ln_start: None,
            lang_label: None,
        }
    }
}

/// Renders one snippet to a `<pre>` block.
///
/// `ranges` maps stripped line index to the ranges on that line.
pub fn render_snippet(
    code: &str,
    tokens: &[Vec<HighlightedText>],
    ranges: &HashMap<usize, Vec<LineRange>>,
    options: &SnippetOptions,
    sheet: &mut StyleSheet,
) -> String {
    let lines: Vec<&str> = code.split('\n').collect();
    // A trailing newline yields one final empty segment; don't render it as
    // an extra blank line.
    let line_count = if lines.last() == Some(&"") {
        lines.len() - 1
    } else {
        lines.len()
    };

    let mut out = String::from("<pre class=\"hl");
    if options.line_numbers {
        out.push_str(" hl-num");
    }
    out.push('"');
    let mut style = String::new();
    if let Some(start) = options.ln_start {
        // The counter increments before each line renders, so reset to one
        // less than the first displayed number.
        let _ = write!(style, "counter-reset: hl-line {};", start - 1);
    }
    if options.line_numbers {
        // The gutter is as wide as the block's widest number, so the code
        // starts where a reader expects it to and short blocks waste no
        // room.
        let last = options.ln_start.unwrap_or(1) + line_count as i64 - 1;
        let _ = write!(style, "--hl-ln-digits: {};", last.max(1).to_string().len());
    }
    if !style.is_empty() {
        let _ = write!(out, " style=\"{style}\"");
    }
    out.push_str("><code class=\"nohighlight\" data-noescape");
    if let Some(label) = &options.lang_label {
        let _ = write!(out, " data-lang=\"{}\"", escape_attr(label));
    }
    out.push('>');

    for i in 0..line_count {
        let line = lines.get(i).copied().unwrap_or("");
        let line_tokens = tokens.get(i).map_or(&[][..], Vec::as_slice);
        let line_ranges = ranges.get(&i).map_or(&[][..], Vec::as_slice);
        // The newline lives inside the line span so selection and copy
        // preserve line structure (blank lines included) without relying on
        // CSS block layout.
        out.push_str("<span class=\"hl-l\">");
        render_line(line, line_tokens, line_ranges, sheet, &mut out);
        out.push_str("\n</span>");
    }

    out.push_str("</code></pre>");
    out
}

/// Cut positions and covering-set changes happen in grapheme columns; the
/// line is treated as extended with virtual spaces up to the furthest range.
fn render_line(
    line: &str,
    tokens: &[HighlightedText],
    ranges: &[LineRange],
    sheet: &mut StyleSheet,
    out: &mut String,
) {
    let graphemes: Vec<&str> = line.graphemes(true).collect();
    let real_len = graphemes.len();
    let virtual_len = ranges.iter().map(|r| r.end_col).fold(real_len, usize::max);

    // Cut points: token boundaries and range boundaries, in grapheme columns.
    let mut cuts: Vec<usize> = vec![0, real_len, virtual_len];
    let mut token_starts = Vec::with_capacity(tokens.len());
    let mut col = 0;
    for tok in tokens {
        token_starts.push(col);
        col += tok.text.graphemes(true).count();
        cuts.push(col.min(virtual_len));
    }
    for r in ranges {
        cuts.push(r.start_col.min(virtual_len));
        cuts.push(r.end_col.min(virtual_len));
    }
    cuts.sort_unstable();
    cuts.dedup();

    let mut open: Vec<usize> = Vec::new();
    let mut opened_once = vec![false; ranges.len()];
    // The token covering the current piece; pieces are visited in order and
    // never straddle a token boundary.
    let mut token = 0;
    for (&start, &end) in cuts.iter().zip(&cuts[1..]) {
        // Desired covering set for this piece, in nesting order.
        let mut desired: Vec<usize> = (0..ranges.len())
            .filter(|&i| ranges[i].start_col <= start && end <= ranges[i].end_col)
            .collect();
        desired.sort_by(|&a, &b| nesting_order(&ranges[a], &ranges[b]));

        // Close/open spans down to the common prefix with what's open. A
        // range reopened after a forced close (partial overlap) is a
        // continuation even if its `first` flag is set.
        let common = open
            .iter()
            .zip(&desired)
            .take_while(|(a, b)| a == b)
            .count();
        for _ in common..open.len() {
            out.push_str("</span>");
            open.pop();
        }
        for &i in &desired[common..] {
            let r = &ranges[i];
            open_fragment_span(r, r.first && !opened_once[i], out);
            opened_once[i] = true;
            open.push(i);
        }

        // The piece text: real graphemes, then virtual spaces.
        if start < real_len {
            while token + 1 < tokens.len() && token_starts[token + 1] <= start {
                token += 1;
            }
            let text: String = graphemes[start..end.min(real_len)].concat();
            render_text(&text, tokens.get(token), sheet, out);
        }
        if end > real_len {
            out.push_str(&" ".repeat(end - start.max(real_len)));
        }
    }
    for _ in &open {
        out.push_str("</span>");
    }
}

/// Nesting order within a piece: whole-line ranges outermost, then
/// earlier-opening ranges outside later ones, longer outside shorter, then by
/// index.
fn nesting_order(a: &LineRange, b: &LineRange) -> Ordering {
    (a.kind == RangeKind::Inline)
        .cmp(&(b.kind == RangeKind::Inline))
        .then(a.start_col.cmp(&b.start_col))
        .then(b.end_col.cmp(&a.end_col))
        .then(a.index.cmp(&b.index))
}

fn open_fragment_span(r: &LineRange, first: bool, out: &mut String) {
    out.push_str("<span class=\"fragment ");
    out.push_str(match r.kind {
        RangeKind::Inline => "highlight-code",
        RangeKind::Lines => "highlight-lines",
    });
    if !first {
        out.push_str(" hl-cont");
    }
    out.push('"');
    let _ = write!(out, " data-fragment-index=\"{}\"", r.index);
    // Only the first opened span of a range carries the note, so a future
    // callout consumer sees it exactly once.
    if first && let Some(note) = &r.note {
        let _ = write!(out, " data-note=\"{}\"", escape_attr(note));
    }
    out.push('>');
}

/// Emits one piece of text with its token style, wrapping emoji runs for
/// font selection.
fn render_text(
    text: &str,
    token: Option<&HighlightedText>,
    sheet: &mut StyleSheet,
    out: &mut String,
) {
    let class = token.and_then(|t| match t.style {
        ThemeVariant::Single(style) => sheet.class_for(style),
        ThemeVariant::Dual { .. } => unreachable!("a single theme is requested"),
    });
    if let Some(class) = &class {
        let _ = write!(out, "<span class=\"{class}\">");
    }
    let mut rest = text;
    while !rest.is_empty() {
        let is_emoji = rest.graphemes(true).next().is_some_and(is_emoji_grapheme);
        let split = rest
            .grapheme_indices(true)
            .find(|(_, g)| is_emoji_grapheme(g) != is_emoji)
            .map_or(rest.len(), |(i, _)| i);
        let (run, tail) = rest.split_at(split);
        if is_emoji {
            out.push_str("<span class=\"hl-emoji\">");
            out.push_str(&escape_text(run));
            out.push_str("</span>");
        } else {
            out.push_str(&escape_text(run));
        }
        rest = tail;
    }
    if class.is_some() {
        out.push_str("</span>");
    }
}

/// Whether a grapheme renders as an emoji rather than a text glyph: VS16
/// forces emoji presentation, the main emoji planes always are, and the
/// legacy symbol blocks only count when they render double-width (which
/// excludes text glyphs like `✓` and `★` that would otherwise lose their
/// monospace metrics to the emoji font).
fn is_emoji_grapheme(g: &str) -> bool {
    g.chars().any(|c| {
        let c = c as u32;
        c == 0xFE0F
            || (0x1F000..=0x1FAFF).contains(&c)
            || ((0x2600..=0x2BFF).contains(&c) && UnicodeWidthStr::width(g) >= 2)
    })
}

fn escape_text(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn escape_attr(s: &str) -> String {
    escape_text(s).replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn style(r: u8) -> Style {
        Style {
            foreground: Color::from_hex(&format!("#{r:02x}0000")).unwrap(),
            background: Color::from_hex("#000000").unwrap(),
            font_style: FontStyle::default(),
        }
    }

    fn tok(text: &str, s: Style) -> HighlightedText {
        HighlightedText {
            text: text.to_string(),
            style: ThemeVariant::Single(s),
        }
    }

    fn default_style() -> Style {
        style(0)
    }

    fn render_with(
        code: &str,
        tokens: Vec<Vec<HighlightedText>>,
        ranges: HashMap<usize, Vec<LineRange>>,
        options: &SnippetOptions,
        sheet: &mut StyleSheet,
    ) -> String {
        render_snippet(code, &tokens, &ranges, options, sheet)
    }

    fn render(
        code: &str,
        tokens: Vec<Vec<HighlightedText>>,
        ranges: HashMap<usize, Vec<LineRange>>,
    ) -> String {
        let options = SnippetOptions {
            line_numbers: false,
            ..Default::default()
        };
        render_with(
            code,
            tokens,
            ranges,
            &options,
            &mut StyleSheet::new(default_style()),
        )
    }

    fn range(start: usize, end: usize, index: u32) -> LineRange {
        LineRange {
            start_col: start,
            end_col: end,
            index,
            kind: RangeKind::Inline,
            first: true,
            note: None,
        }
    }

    #[test]
    fn plain_line() {
        let html = render(
            "f();\n",
            vec![vec![tok("f();", default_style())]],
            HashMap::new(),
        );
        assert_eq!(
            html,
            "<pre class=\"hl\"><code class=\"nohighlight\" data-noescape>\
             <span class=\"hl-l\">f();\n</span></code></pre>"
        );
    }

    #[test]
    fn styled_token_gets_class() {
        let html = render("fn", vec![vec![tok("fn", style(1))]], HashMap::new());
        assert!(html.contains("<span class=\"hl-t0\">fn</span>"), "{html}");
    }

    #[test]
    fn fragment_splits_token() {
        let mut ranges = HashMap::new();
        ranges.insert(0, vec![range(2, 4, 1)]);
        let html = render("abcdef", vec![vec![tok("abcdef", style(1))]], ranges);
        // Token split into three pieces, middle one wrapped in the fragment.
        assert!(
            html.contains(
                "<span class=\"hl-t0\">ab</span><span class=\"fragment highlight-code\" \
                 data-fragment-index=\"1\"><span class=\"hl-t0\">cd</span></span>\
                 <span class=\"hl-t0\">ef</span>"
            ),
            "{html}"
        );
    }

    #[test]
    fn fragment_spans_tokens() {
        let mut ranges = HashMap::new();
        ranges.insert(0, vec![range(0, 4, 2)]);
        let html = render(
            "abcd",
            vec![vec![tok("ab", style(1)), tok("cd", style(2))]],
            ranges,
        );
        assert!(
            html.contains(
                "<span class=\"fragment highlight-code\" data-fragment-index=\"2\">\
                 <span class=\"hl-t0\">ab</span><span class=\"hl-t1\">cd</span></span>"
            ),
            "{html}"
        );
    }

    #[test]
    fn partial_overlap_nests_and_splits() {
        let mut ranges = HashMap::new();
        ranges.insert(0, vec![range(0, 4, 1), range(2, 6, 2)]);
        let html = render("abcdef", vec![vec![tok("abcdef", default_style())]], ranges);
        // A covers [0,4), B covers [2,6): B is split at A's close, and its
        // continuation reopens outside A with the hl-cont marker.
        assert!(html.contains("data-fragment-index=\"1\">ab<span"), "{html}");
        assert!(
            html.contains("data-fragment-index=\"2\">cd</span></span>"),
            "{html}"
        );
        assert!(
            html.contains("hl-cont\" data-fragment-index=\"2\">ef</span>"),
            "{html}"
        );
    }

    #[test]
    fn virtual_space_padding() {
        let mut ranges = HashMap::new();
        ranges.insert(0, vec![range(5, 8, 1)]);
        let html = render("f();", vec![vec![tok("f();", default_style())]], ranges);
        assert!(
            html.contains("data-fragment-index=\"1\">   </span>"),
            "{html}"
        );
    }

    #[test]
    fn whole_line_wrapper() {
        let mut ranges = HashMap::new();
        ranges.insert(
            0,
            vec![LineRange {
                start_col: 0,
                end_col: 4,
                index: 3,
                kind: RangeKind::Lines,
                first: true,
                note: None,
            }],
        );
        let html = render("f();", vec![vec![tok("f();", default_style())]], ranges);
        assert!(
            html.contains(
                "<span class=\"hl-l\"><span class=\"fragment highlight-lines\" \
                 data-fragment-index=\"3\">f();</span>\n</span>"
            ),
            "{html}"
        );
    }

    #[test]
    fn emoji_wrapped() {
        let html = render(
            "// \u{274c} bad",
            vec![vec![tok("// \u{274c} bad", default_style())]],
            HashMap::new(),
        );
        assert!(
            html.contains("// <span class=\"hl-emoji\">\u{274c}</span> bad"),
            "{html}"
        );
    }

    #[test]
    fn escapes_html() {
        let html = render(
            "a<b>&c",
            vec![vec![tok("a<b>&c", default_style())]],
            HashMap::new(),
        );
        assert!(html.contains("a&lt;b&gt;&amp;c"), "{html}");
    }

    #[test]
    fn note_attribute() {
        let mut ranges = HashMap::new();
        let mut r = range(0, 4, 1);
        r.note = Some("the \"why\"".to_string());
        ranges.insert(0, vec![r]);
        let html = render("f();", vec![vec![tok("f();", default_style())]], ranges);
        assert!(html.contains("data-note=\"the &quot;why&quot;\""), "{html}");
    }

    #[test]
    fn line_numbers_and_start() {
        let html = render_with(
            "f();",
            vec![vec![tok("f();", default_style())]],
            HashMap::new(),
            &SnippetOptions {
                line_numbers: true,
                ln_start: Some(10),
                ..Default::default()
            },
            &mut StyleSheet::new(default_style()),
        );
        assert!(
            html.starts_with(
                "<pre class=\"hl hl-num\" style=\"counter-reset: hl-line 9;\
                 --hl-ln-digits: 2;\">"
            ),
            "{html}"
        );
    }

    #[test]
    fn language_badge() {
        let html = render_with(
            "f();",
            vec![vec![tok("f();", default_style())]],
            HashMap::new(),
            &SnippetOptions {
                lang_label: Some("C++".to_string()),
                ..Default::default()
            },
            &mut StyleSheet::new(default_style()),
        );
        assert!(
            html.contains("<code class=\"nohighlight\" data-noescape data-lang=\"C++\">"),
            "{html}"
        );
    }

    #[test]
    fn gutter_widens_with_the_last_number() {
        let mut sheet = StyleSheet::new(default_style());
        let render = |lines: usize, start, sheet: &mut StyleSheet| {
            let code = "f();\n".repeat(lines);
            let tokens: Vec<Vec<HighlightedText>> = (0..lines)
                .map(|_| vec![tok("f();", default_style())])
                .collect();
            render_with(
                &code,
                tokens,
                HashMap::new(),
                &SnippetOptions {
                    line_numbers: true,
                    ln_start: start,
                    ..Default::default()
                },
                sheet,
            )
        };
        assert!(render(9, None, &mut sheet).contains("--hl-ln-digits: 1;"));
        assert!(render(10, None, &mut sheet).contains("--hl-ln-digits: 2;"));
        assert!(render(100, None, &mut sheet).contains("--hl-ln-digits: 3;"));
        // An offset start counts toward the widest number, not the count.
        assert!(render(2, Some(99), &mut sheet).contains("--hl-ln-digits: 3;"));
    }

    #[test]
    fn stylesheet_dedup() {
        let mut sheet = StyleSheet::new(default_style());
        for _ in 0..2 {
            render_with(
                "fn",
                vec![vec![tok("fn", style(1))]],
                HashMap::new(),
                &SnippetOptions::default(),
                &mut sheet,
            );
        }
        let scss = sheet.to_scss();
        assert_eq!(scss.matches(".hl-t0").count(), 1, "{scss}");
        assert!(scss.contains("pre.hl {\n  color: #000000;\n}"), "{scss}");
        assert!(scss.contains(".hl-t0 {\n  color: #010000;\n}"), "{scss}");
        assert!(!scss.contains("background"), "{scss}");
    }

    #[test]
    fn empty_line_renders_span() {
        let html = render(
            "a\n\nb",
            vec![
                vec![tok("a", default_style())],
                vec![],
                vec![tok("b", default_style())],
            ],
            HashMap::new(),
        );
        assert!(html.contains("<span class=\"hl-l\">\n</span>"), "{html}");
    }

    #[test]
    fn text_glyphs_not_emoji_wrapped() {
        let html = render(
            "// \u{2713} ok \u{2605}",
            vec![vec![tok("// \u{2713} ok \u{2605}", default_style())]],
            HashMap::new(),
        );
        assert!(!html.contains("hl-emoji"), "{html}");
    }

    #[test]
    fn note_only_on_first_span_of_split_range() {
        let mut ranges = HashMap::new();
        let mut a = range(0, 4, 1);
        a.note = Some("n".to_string());
        let mut b = range(2, 6, 2);
        b.note = Some("m".to_string());
        ranges.insert(0, vec![a, b]);
        let html = render("abcdef", vec![vec![tok("abcdef", default_style())]], ranges);
        assert_eq!(html.matches("data-note=\"m\"").count(), 1, "{html}");
        assert_eq!(html.matches("data-note=\"n\"").count(), 1, "{html}");
    }
}
